### ISSUE TITLE
Use external MySQL database

### ISSUE THREAD

**Issue by jacksgt** [vision-it/vision-mbl#4]
Use `vision_mysql` instead of local database container.

**Comment by jacksgt** [comment]
Debian 8 Jessie ships with MySQL 5.5, which does not support long indices:
```
mysql -u root -p mbl < mbl_2018-05-02.sql 
Enter password: 
ERROR 1071 (42000) at line 33: Specified key was too long; max key length is 767 bytes
```
https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes#16820166

**Comment by martialblog** [comment]
FYI, you should rebase the Branch if you continue

**Comment by martialblog** [comment]
Should be fixed when we change to swarm.
