### ISSUE TITLE
Use vision path for mbl data

### ISSUE THREAD

**Issue by jacksgt** [vision-it/vision-mbl#5]
Use `/vision/data/mbl` for application data, as per https://github.com/vision-it/vision-default/issues/12

**Comment by martialblog** [comment]
Hab die https://github.com/vision-it/vision-mbl/tree/dirs Branch jetzt rebased und den WIP Commit auf ne neue Branch gehauen. 

Kann man das mergen?

**Comment by jacksgt** [comment]
Ja, die Daten müssen dann aber auch in der Produktion auf den neuen Pfad verschoben werden.

**Comment by martialblog** [comment]
Alles klar
